### PR TITLE
add wrappers for getReverseRoute with MethodReferences.

### PR DESCRIPTION
**Pull request by awildturtok**
This makes writing templates a lot cleaner, and adds static typechecking.

### CODE REVIEW

**Comment by jjlauer** [comment]
MethodReference only exists in Ninja 5.4.0+, but ninja-rocker is currently targeting Ninja 5.3.1.  In order to accept this PR, you'd need to bump up the ninja dependency, and ideally add at least 1 unit test.

**Comment by awildturtok** [comment]
I don't actually think this does what I thought it does. It seemed to work, but my guess is that I just misread something or missed placing an @ somewhere. Sorry.

**Comment by jjlauer** [comment]
@awildturtok What were thinking it should do?

**Comment by awildturtok** [comment]
I expected it to allow references in the style of class::method, but while trying to create a testcase it didn't compile, and digging into ninja it seems that MethodReference is just a container for (Class.class,"method"). Maybe I mistook it, and it works, but I had no time digging deeper.

**Comment by jjlauer** [comment]
MethodReference will eventually allow you to use the syntax class::method.
Since Ninja still supports Java 7, I added the MethodReference concept to
Ninja to eventually allow Java 8-style references even with Ninja still on
Java 7.

I haven't had time to adapt my ninja-java8 project to work with the new
MethodReference, but your instinct is correct that hopefully it'll work
pretty soon.

https://github.com/fizzed/ninja-java8

**Pull request closed without merging**
