### PR TITLE
made ninja context available in subclasses of NinjaRockerTemplate

### PR DESCRIPTION
**Pull request by jshinobi**
I am not good at english naming
it's just the idea.

### CODE REVIEW

**Comment by jjlauer** [comment]
hey @jshinobi -- seems like you want the Ninja context accessible within the template?  I remember hiding it on purpose as it seemed like it promoted a better template code by not allowing you to do things better left in the controller.  Curious what you're actually using in the context in the template that you'd suggest explicitly providing it to templates?

**Comment by jshinobi** [comment]
Restrictions on purpose - it's java way which brought me a lot of pain in my life :-)
I like package structure like com.company.project.{views,controllers,models)
There is one project which contains a lot of small sub-projects, for me much easier maintain all of them in one workspace(folder).But they have own conf files and run independetly
And it's really convinient if I don't need to hardcode the each sub-project's asset path, instead of @N.assetsAt("subproject/main.css") I could write @L.assetsAt("main.css") and assetsAt able route it depending on current conf file(this.reverseRoute(AssetsController.class, "serveStatic", "fileName", ninjaProperties.get("assets.prefix") + file);).
So we need router to make life better.

Also, I don't know how people connect views with controllers without context, for example there is template in template in template, and I want pass some var to it. I have to declare it in all views args, even it does not have any relation to any of them except the last one, so args of template would grow and it hard to mantain them without ide support. I could put in context some validation information, menu information and so on. I prefer transfer main data through args, in this case, it is easy made auto json content negation. And you need to do it manually for each method if you pass to view something like this render(data,validation,menu,some other stuff)

One day, I was thinking about displaying active menu link.I thought If I could make helper  isActive(String url) , it will compare url with current(we need context) and return "active" - simple, cool, but impossible because of restrictions :-)

And there is a lot of small cases like this.

Anyway it is your project - and I respect owner's decision

**Comment by jshinobi** [comment]
one more use case: If  we decide to add auth system, then in templates we could use something like this
if( @L.userLoggedIn()){
   stuff
}else{
  other stuff
}
if (@L.userHasRole("admin")){...}
if we have no context, we have to change all our template args to render(data,validation,menuList,user)...

By the way, Even if you get context, you cannot get access to cache in the  RockerTempate. @Inject NinjaCache returns null. That's a problem if you load users through cache

That's the java way, sometimes there is no easy way to do easy things :-)

**Comment by jjlauer** [comment]
@jshinobi Thanks for sharing your use cases.  I run into the same issues myself.  Your fancy "assetsAt" method is pretty cool and I see why accessing the context, router, etc. is invaluable for that to work. I'll have to think a little more about what you proposed.  As far as your "User" example, isn't adding something like a `User` object to each template render really what you should be doing?  You could then unit test your templates by injecting a mock/real User object.  So rather than `L.userLoggedIn` you could do something like `@if (user != null) {` and then `@if (user.hasRole("admin")) {`.  The obvious annoyance with this approach is that you'd have to add a `User user` argument to each template.  I guess my obvious question is how do you lookup a User object on each request?  Are you setting it as an attribute on the context?  Do you look it up in each controller method already?

**Comment by jshinobi** [comment]
> As far as your "User" example, isn't adding something like a User object to each template render really what you should be doing? You could then unit test your templates by injecting a mock/real User object. 

To my shame I don't use tests. That's why I cannot discuss the topic and give any advices. It's not a big problem to me get bugs in production sometimes. The price of bugs much smaller the time I would spent on writing and maintaining tests. That's why I only care about fancy and easy style of programming and "you'd have to add a User user argument to each template" cares me a lot :-)
In my defence we didn't have  any critical bugs for the past 8 years, and amount of bugs the same or less comparing to java enterprise companies using tests :-)
Actually static compiled language and static compiled views(that's why I think your views are awesome) covers all my needs  and replaces tests in my case. Of course it only works if you are quite clever and small company and it is not community maintained lib(project). But the development, refactoring speed and motivation in this rare case are truly amazing :-)

> Are you setting it as an attribute on the context? Do you look it up in each controller method already?

Yes, the idea is simple:
BaseController extends ...{
...
 /**
     \* if user logged in
     *
     \* @param session
     \* @return
     */
    public static boolean loggedIn(Session session) {
        return session.get(UserLogInjecter.USERNAME) != null;
    }

```
public static User user(Session session) {
    final String username = session.get(UserLogInjecter.USERNAME);
    if (StringUtils.isEmpty(username)) {
        throw new InternalServerErrorException("user not logged in or empty user name");
    }
    //key= userName:login
    String cacheKey = String.format(CACHE_KEY_PATTERN, username);
    User user = cache.get(cacheKey, User.class);

    if (user == null) {
        user = User.dao.findByUserName(username);
        if (user == null) {
            throw new InternalServerErrorException("unknown user to db");
        }
        cache.add(cacheKey, user);
    }
    return user;
}

public static void setUser(Session session, User user) {
    //key= userName:login
    String cacheKey = String.format(CACHE_KEY_PATTERN, user.getUserName());
    cache.add(cacheKey, user);
    session.put(UserLogInjecter.USERNAME, user.getUserName());
}

public static void clearSession(Session session) {
    if (loggedIn(session)) {
        final String username = session.get(UserLogInjecter.USERNAME);
        //key= userName:login
        String cacheKey = String.format(CACHE_KEY_PATTERN, username);
        cache.safeDelete(cacheKey);
    }
    session.clear();
}
```

}
You just call setUser in login method, and that's all.
P.S these methods are static because I use them in views helpers, also i have non static controllers methods  like public User user() { return user(getSession()); }

**Comment by jfendler** [comment]
I would also  support @jshinobi 's approach of exposing more of Ninja's internals through Rocker.

Personally, I use a similar approach of having a User object fetched from the DB by a filter which then sets a context attribute with the User object.
Since 90% of all my controller methods (and their templates) make use of the User object, I don't favour the idea of specifying this as a parameter for each controller which could then be injected. (I'd rather have to specify something when there is NO Use ;-)

Within the template, the Context is nice to have for things like requestPath(), remoteAddr(), and similar things, and I use NinjaProperties for some template-level configuration as well.

To be able to access these in my templates (and extend the possibilities of the "N" object accordingly) I now had to subclass/replace all of NinjaRocker, NinjaRockerModule, NinjaRockerTemplate and TemplateEngineRocker with my own versions thereof - only to be able to get access to what is already available to the existing classes (internally).

I would suggest making all of the private fields either public, or - if there are too strong objections against this - perhaps provide public accessor methods for them. As a last resort, make them "protected" rather than private so that at least subclasses can chose to re-expose the fields if need be.

I remember Ninja's FreemarkerEngine using the same (highly limited) approach. But at least its FreemarkerConfiguration is exposed and accessible for custom extensions now. Maybe a similar path could work for Rocker as well? (Needless to say, I don't plan on going back to Freemarker for this - Rocker is pretty awesome).

**Comment by jjlauer** [comment]
Fixed in v0.12.0 - you persuaded me that context should be public.  You should also take a look at the new demonstration of Application-specific templates.  Appreciate the PR, but I tweaked both Rocker and Ninja-Rocker do support everything a bit more elegantly.  Take a look the updated docs and demo app.

**Pull request closed without merging**
